spring:
  application:
    name: ApiGateway

  datasource:
    url: jdbc:mysql://localhost:3306/capstone
    username: root
    password: pass@word1
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update  # Consider changing to 'validate' or 'none' in production
    show-sql: true

  cloud:
    gateway:
      routes:
        - id: carbonTrack-route
          uri: lb://CARBONFOOTPRINTTRACK
          predicates:
            - Path=/carbonTrack/**

        - id: communityservice-route
          uri: lb://COMMUNITYSERVICE
          predicates:
            - Path=/community/**

    discovery:
      enabled: true

    eureka:
      client:
        service-url:
          defaultZone: http://localhost:8761/eureka/
        register-with-eureka: true
        fetch-registry: true

      instance:
        hostname: localhost
        instance-id: ${spring.application.name}:${instanceId:${random.value}}

management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 9999

#logging:
#  level:
#    org.springframework: DEBUG

security:
  jwt:
    secret-key: 3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
    expiration-time: 86400000
